CREATE TABLE ABILITY (
    id UUID NOT NULL,
    ability_type VARCHAR(10) NOT NULL,
    description VARCHAR(1000) NOT NULL,
    name VARCHAR(100) NOT NULL,
    PRIMARY KEY (id)
);

CREATE TABLE ABILITY_SKILLS (
    ability_id UUID NOT NULL,
    skills_id UUID NOT NULL,
    PRIMARY KEY (ability_id, skills_id)
);

CREATE TABLE CHARACTER (
    id UUID NOT NULL,
    age INT4 NOT NULL,
    appearence VARCHAR(500),
    biography VARCHAR(1000) NOT NULL,
    gender VARCHAR(10) NOT NULL,
    image BYTEA,
    name VARCHAR(100) NOT NULL,
    temper VARCHAR(500) NOT NULL,
    race_id UUID NOT NULL,
    PRIMARY KEY (id)
);

CREATE TABLE CHARACTER_ABILITY (
    character_id UUID NOT NULL,
    ability_id UUID NOT NULL,
    PRIMARY KEY (character_id, ability_id)
);

CREATE TABLE CHARACTER_CHARACTERISTIC (
    character_id UUID NOT NULL,
    characteristic_id UUID NOT NULL,
    PRIMARY KEY (character_id, characteristic_id)
);

CREATE TABLE CHARACTER_MAGIC (
    character_id UUID NOT NULL,
    magic_id UUID NOT NULL,
    PRIMARY KEY (character_id, magic_id)
);

CREATE TABLE CHARACTERISTIC (
    id UUID NOT NULL,
    description VARCHAR(1000) NOT NULL,
    level INT4 NOT NULL,
    name VARCHAR(100) NOT NULL,
    PRIMARY KEY (id)
);

CREATE TABLE MAGIC (
    id UUID NOT NULL,
    description VARCHAR(1000) NOT NULL,
    name VARCHAR(100) NOT NULL,
    PRIMARY KEY (id)
);

CREATE TABLE MAGIC_SPELLS (
    magic_id UUID NOT NULL,
    spells_id UUID NOT NULL,
    PRIMARY KEY (magic_id, spells_id)
);

CREATE TABLE RACE (
    id UUID NOT NULL,
    description VARCHAR(1000) NOT NULL,
    name VARCHAR(100) NOT NULL,
    PRIMARY KEY (id)
);

CREATE TABLE SKILL (
    id UUID NOT NULL,
    description VARCHAR(1000) NOT NULL,
    min_level INT4 NOT NULL,
    PRIMARY KEY (id)
);

CREATE TABLE SPELL (
    id UUID NOT NULL,
    description VARCHAR(1000) NOT NULL,
    level INT4 NOT NULL,
    name VARCHAR(100),
    PRIMARY KEY (id)
);


ALTER TABLE IF EXISTS MAGIC_SPELLS ADD CONSTRAINT uk_spells UNIQUE (spells_id);
ALTER TABLE IF EXISTS MAGIC_SPELLS ADD CONSTRAINT fk_spells FOREIGN KEY (spells_id) REFERENCES spellEO(id);
ALTER TABLE IF EXISTS MAGIC_SPELLS ADD CONSTRAINT fk_magic FOREIGN KEY (magic_id) REFERENCES magicEO(id);
ALTER TABLE IF EXISTS CHARACTER_MAGIC ADD CONSTRAINT fk_magic FOREIGN KEY (magic_id) REFERENCES magicEO(id);
ALTER TABLE IF EXISTS CHARACTER_MAGIC ADD CONSTRAINT fk_character FOREIGN KEY (character_id) REFERENCES character(id);
ALTER TABLE IF EXISTS CHARACTER_CHARACTERISTIC ADD CONSTRAINT fk_characteristic FOREIGN KEY (characteristic_id) REFERENCES magicEO(id);
ALTER TABLE IF EXISTS CHARACTER_CHARACTERISTIC ADD CONSTRAINT fk_character FOREIGN KEY (character_id) REFERENCES character(id);
ALTER TABLE IF EXISTS CHARACTER_ABILITY ADD CONSTRAINT fk_ability FOREIGN KEY (ability_id) REFERENCES magicEO(id);
ALTER TABLE IF EXISTS CHARACTER_ABILITY ADD CONSTRAINT fk_character FOREIGN KEY (character_id) REFERENCES character(id);
ALTER TABLE IF EXISTS CHARACTER ADD CONSTRAINT fk_race FOREIGN KEY (race_id) REFERENCES race(id);
ALTER TABLE IF EXISTS MAGIC_SKILLS ADD CONSTRAINT uk_skills UNIQUE (skills_id);
ALTER TABLE IF EXISTS MAGIC_SKILLS ADD CONSTRAINT fk_skills FOREIGN KEY (skills_id) REFERENCES skill(id);
ALTER TABLE IF EXISTS MAGIC_SKILLS ADD CONSTRAINT fk_ability FOREIGN KEY (ability_id) REFERENCES abilityEO(id);