ALTER TABLE IF EXISTS CHARACTER_MAGIC DROP CONSTRAINT fk_magic;
ALTER TABLE IF EXISTS CHARACTER_MAGIC DROP CONSTRAINT fk_character;
ALTER TABLE IF EXISTS CHARACTER_CHARACTERISTIC DROP CONSTRAINT fk_characteristic;
ALTER TABLE IF EXISTS CHARACTER_CHARACTERISTIC DROP CONSTRAINT fk_character;

DROP TABLE IF EXISTS CHARACTER_CHARACTERISTIC;
DROP TABLE IF EXISTS CHARACTER_MAGIC;
DROP TABLE IF EXISTS CHARACTERISTIC;

ALTER TABLE CHARACTER
  ADD aim VARCHAR(100) NOT NULL,
  ADD nationality VARCHAR(100) NOT NULL;

CREATE TABLE CHARACTER_SPELL (
    character_id UUID NOT NULL,
    spell_id UUID NOT NULL,
    PRIMARY KEY (character_id, spell_id)
);

ALTER TABLE IF EXISTS CHARACTER_SPELL ADD CONSTRAINT fk_spell FOREIGN KEY (spell_id) REFERENCES spellEO(id);
ALTER TABLE IF EXISTS CHARACTER_SPELL ADD CONSTRAINT fk_character FOREIGN KEY (character_id) REFERENCES character(id);