spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/iridium
    username: postgres
    password: 123
  jpa:
    hibernate:
      ddl-auto: validate
  flyway:
    enabled: true
    baselineOnMigrate: true

security:
  jwt:
    secret-key: 116e50262393df1679aa157ea553b57a2cf25ae8c9f919137a7cde370599be51
    expiration-time: 3600000
#logging:
#  level:
#    org.hibernate: DEBUG
#logging:
#  level:
#    org.springframework: DEBUG

springdoc:
  swagger-ui:
    url: /v3/api-docs
    server.name: /
    disable-swagger-default-url: false
    configUrl: /v3/api-docs/swagger-config