spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/iridium
    username: postgres
    password: 123
  jpa:
    hibernate:
      ddl-auto: validate
  flyway:
    enabled: true
    baselineOnMigrate: true

#logging:
#  level:
#    org.hibernate: DEBUG
#logging:
#  level:
#    org.springframework: DEBUG

springdoc:
  swagger-ui:
    url: /v3/api-docs
    server.name: /
    disable-swagger-default-url: false
    configUrl: /v3/api-docs/swagger-config