openapi: 3.0.3
info:
  title: Iridium - OpenAPI 3.0
  description: Iridium API Spec
  version: 1.0.0
servers:
  - url: http://localhost:8080/api/v1
paths:
  /character:
    $ref: 'rest/character/character.yml'
  /character/{id}:
    $ref: 'rest/character/get-character.yml'
  /character/generate:
    $ref: 'rest/character/generate-character.yml'

  /ability:
    $ref: 'rest/ability/ability.yml'
  /ability/{id}:
    $ref: 'rest/ability/get-ability.yml'

  /magic:
    $ref: 'rest/magic/magic.yml'
  /magic/{id}:
    $ref: 'rest/magic/get-magic.yml'

  /race:
    $ref: 'rest/race/race.yml'
  /race/{id}:
    $ref: 'rest/race/get-race.yml'

  /authorization/login:
    $ref: 'rest/user/login.yml'
  /authorization/register:
    $ref: 'rest/user/register.yml'
  /authorization/user:
    $ref: 'rest/user/user.yml'