openapi: 3.0.3
info:
  title: Iridium - OpenAPI 3.0
  description: Iridium API Spec
  version: 1.0.0
servers:
  - url: http://localhost:8080/api/v1
paths:
  /character:
    $ref: 'rest/character/character.yaml'
  /character/{id}:
    $ref: 'rest/character/get-character.yaml'

  /ability:
    $ref: 'rest/ability/ability.yaml'
  /ability/{id}:
    $ref: 'rest/ability/get-ability.yaml'

  /magic:
    $ref: 'rest/magic/magic.yaml'
  /magic/{id}:
    $ref: 'rest/magic/get-magic.yaml'

  /race:
    $ref: 'rest/race/race.yaml'
  /race/{id}:
    $ref: 'rest/race/get-race.yaml'